package org.ericwubbo.pagingdemo;

import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class Seeder implements CommandLineRunner {

    private final ItemRepository itemRepository;

    @Override
    public void run(String... args) {
        if (itemRepository.count() == 0) {
            itemRepository.saveAll(List.of(
                    new Item("chocolate bar", "2.20"),
                    new Item("syrup waffles", "1.96"),
                    new Item("apple", "0.50"),
                    new Item("banana", "0.30"),
                    new Item("orange juice", "3.00"),
                    new Item("bread loaf", "1.50"),
                    new Item("milk", "1.20"),
                    new Item("cheese", "2.80"),
                    new Item("yogurt", "0.90"),
                    new Item("cereal", "4.50"),
                    new Item("eggs", "2.10"),
                    new Item("butter", "1.70"),
                    new Item("jam", "2.40"),
                    new Item("coffee", "5.00"),
                    new Item("tea", "3.20"),
                    new Item("sugar", "1.00"),
                    new Item("salt", "0.60"),
                    new Item("pepper", "1.50"),
                    new Item("pasta", "1.20"),
                    new Item("rice", "2.00"),
                    new Item("chicken breast", "5.50"),
                    new Item("beef steak", "10.00"),
                    new Item("pork chops", "6.50"),
                    new Item("fish fillet", "7.20"),
                    new Item("shrimp", "12.00"),
                    new Item("crackers", "2.80"),
                    new Item("chips", "1.80"),
                    new Item("pretzels", "1.50"),
                    new Item("nuts", "3.40"),
                    new Item("raisins", "2.10"),
                    new Item("dates", "3.60"),
                    new Item("popcorn", "1.00"),
                    new Item("frozen pizza", "4.00"),
                    new Item("ice cream", "3.50"),
                    new Item("frozen vegetables", "2.00"),
                    new Item("frozen berries", "3.80"),
                    new Item("ketchup", "1.50"),
                    new Item("mustard", "1.20"),
                    new Item("mayonnaise", "2.00"),
                    new Item("hot sauce", "2.50"),
                    new Item("soy sauce", "1.80"),
                    new Item("olive oil", "6.00"),
                    new Item("vegetable oil", "3.00"),
                    new Item("vinegar", "1.50"),
                    new Item("honey", "4.20"),
                    new Item("maple syrup", "5.00"),
                    new Item("peanut butter", "2.80"),
                    new Item("jelly", "2.40"),
                    new Item("spaghetti sauce", "2.50"),
                    new Item("tortillas", "2.20"),
                    new Item("bagels", "1.90"),
                    new Item("croissants", "3.00"),
                    new Item("english muffins", "2.00"),
                    new Item("flour", "1.50"),
                    new Item("baking powder", "1.20"),
                    new Item("yeast", "1.00"),
                    new Item("cinnamon", "2.50"),
                    new Item("vanilla extract", "3.80"),
                    new Item("basil", "1.20"),
                    new Item("oregano", "1.20"),
                    new Item("garlic", "0.80"),
                    new Item("onion", "0.70"),
                    new Item("carrots", "0.90"),
                    new Item("broccoli", "1.20"),
                    new Item("spinach", "1.50"),
                    new Item("lettuce", "1.00"),
                    new Item("tomatoes", "1.80"),
                    new Item("cucumber", "0.80"),
                    new Item("bell peppers", "2.00"),
                    new Item("zucchini", "1.10"),
                    new Item("mushrooms", "1.50"),
                    new Item("potatoes", "1.20"),
                    new Item("sweet potatoes", "1.50"),
                    new Item("corn", "1.00"),
                    new Item("green beans", "1.50"),
                    new Item("peas", "1.20"),
                    new Item("apple juice", "2.50"),
                    new Item("grape juice", "3.00"),
                    new Item("lemonade", "2.00"),
                    new Item("iced tea", "2.20"),
                    new Item("soda", "1.00"),
                    new Item("water", "0.80"),
                    new Item("sparkling water", "1.20"),
                    new Item("energy drink", "2.00"),
                    new Item("beer", "6.00"),
                    new Item("wine", "10.00"),
                    new Item("whiskey", "25.00"),
                    new Item("vodka", "20.00"),
                    new Item("rum", "18.00"),
                    new Item("gin", "22.00"),
                    new Item("tequila", "30.00"),
                    new Item("cookies", "2.50"),
                    new Item("brownies", "3.00"),
                    new Item("cake mix", "2.20"),
                    new Item("pie crust", "2.00"),
                    new Item("pancake mix", "2.40"),
                    new Item("waffle mix", "2.60"),
                    new Item("bread crumbs", "1.50"),
                    new Item("croutons", "1.80"),
                    new Item("beef jerky", "4.00"),
                    new Item("protein bar", "2.50")));
        }
    }
}
